#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export NANOHORIZON_OFFLINE_CONFIG="${NANOHORIZON_OFFLINE_CONFIG:-configs/crafter_offline_qwen35_4b_student_qwen35_9b_proof.yaml}"
export NANOHORIZON_TEACHER_MODEL="${NANOHORIZON_TEACHER_MODEL:-Qwen/Qwen3.5-9B}"
export NANOHORIZON_TEACHER_ENFORCE_EAGER="${NANOHORIZON_TEACHER_ENFORCE_EAGER:-1}"
export NANOHORIZON_TEACHER_MAX_MODEL_LEN="${NANOHORIZON_TEACHER_MAX_MODEL_LEN:-8192}"
export NANOHORIZON_MIN_TEACHER_REWARD="${NANOHORIZON_MIN_TEACHER_REWARD:-1.0}"
export NANOHORIZON_MAX_TEACHER_ROWS="${NANOHORIZON_MAX_TEACHER_ROWS:-8}"
export NANOHORIZON_FILTER_COLLECT_WOOD="${NANOHORIZON_FILTER_COLLECT_WOOD:-1}"

exec "$ROOT/scripts/run_crafter_offline_qwen35_4b_1xa100_20min.sh" "$@"
