#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
export NANOHORIZON_OFFLINE_CONFIG="${NANOHORIZON_OFFLINE_CONFIG:-configs/crafter_offline_reference.yaml}"
export NANOHORIZON_STUDENT_MODEL="${NANOHORIZON_STUDENT_MODEL:-Qwen/Qwen3.5-4B}"
export NANOHORIZON_TEACHER_MODEL="${NANOHORIZON_TEACHER_MODEL:-Qwen/Qwen3.5-9B}"
export NANOHORIZON_THINKING_BUDGET_TOKENS="${NANOHORIZON_THINKING_BUDGET_TOKENS:-2000}"
export NANOHORIZON_MAX_NEW_TOKENS="${NANOHORIZON_MAX_NEW_TOKENS:-2200}"
export NANOHORIZON_MAX_MODEL_LEN="${NANOHORIZON_MAX_MODEL_LEN:-8192}"
export NANOHORIZON_NUM_EVAL_ROLLOUTS="${NANOHORIZON_NUM_EVAL_ROLLOUTS:-20}"
export NANOHORIZON_EVAL_MAX_CONCURRENCY="${NANOHORIZON_EVAL_MAX_CONCURRENCY:-10}"
export NANOHORIZON_EVAL_MAX_STEPS="${NANOHORIZON_EVAL_MAX_STEPS:-8}"
export NANOHORIZON_EVAL_REQUEST_TIMEOUT_SECONDS="${NANOHORIZON_EVAL_REQUEST_TIMEOUT_SECONDS:-600}"
export NANOHORIZON_MODAL_GPU_OFFLINE="${NANOHORIZON_MODAL_GPU_OFFLINE:-A100-40GB}"
export NANOHORIZON_MIN_TEACHER_REWARD="${NANOHORIZON_MIN_TEACHER_REWARD:-1.0}"
export NANOHORIZON_MAX_TEACHER_ROWS="${NANOHORIZON_MAX_TEACHER_ROWS:-8}"
export NANOHORIZON_FILTER_COLLECT_WOOD="${NANOHORIZON_FILTER_COLLECT_WOOD:-1}"

exec ./scripts/run_offline_training.sh "$@"
